### ISSUE TITLE
[PE-D][Tester D] Help does not show the link to team's UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T10-2/tp#154] opened 2024-04-05 19:20 UTC
Instead, it displays the link to AB3

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: erv-teo/ped#10

**Comment by legionlegion** [comment] 2024-04-06 14:02
closed by #167

**Closed by legionlegion** 2024-04-06 14:02 UTC

**Comment by chengjunyuan** [comment] 2024-04-10 13:30
Also a duplicate of #178
